package day8

import (
	"testing"
)

func TestSample(t *testing.T) {
	sampleData := `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`

	ans1, ans2 := Solve(sampleData)
	if ans1 != 14 {
		t.Fatalf("Mismatch! Expected 14 got %d", ans1)
	}
	if ans2 != 34 {
		t.Fatalf("Mismatch! Expected 34 got %d", ans2)
	}
}
